# Generated by Django 4.1.5 on 2023-01-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="cars", table="Cars",),
    ]
